"""empty message

Revision ID: 1d7d6bdaac2b
Revises: e24919beff0d
Create Date: 2022-05-26 02:49:05.554314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7d6bdaac2b'
down_revision = 'e24919beff0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('description', sa.String(length=400), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'description')
    # ### end Alembic commands ###
