"""empty message

Revision ID: 9e8b4f3433a0
Revises: 9cbf6c3ae899
Create Date: 2022-05-24 02:41:21.020405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8b4f3433a0'
down_revision = '9cbf6c3ae899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('gender', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'gender')
    # ### end Alembic commands ###
