"""empty message

Revision ID: e24919beff0d
Revises: 4cf6c1291552
Create Date: 2022-05-26 02:48:38.357096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e24919beff0d'
down_revision = '4cf6c1291552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('description', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
